name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Smoke test imports
        run: |
          python - <<'PY'
          import streamlit, ultralytics, mtcnn, deepface, cv2, numpy, pandas
          print("Imports OK")
          PY

      - name: Streamlit syntax check
        run: python -m py_compile app.py
